/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HospitalAdminIndexRouteImport } from './routes/hospital-admin.index'
import { Route as HospitalIdRouteImport } from './routes/hospital.$id'
import { Route as HospitalAdminLoginRouteImport } from './routes/hospital-admin.login'

const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalAdminIndexRoute = HospitalAdminIndexRouteImport.update({
  id: '/hospital-admin/',
  path: '/hospital-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalIdRoute = HospitalIdRouteImport.update({
  id: '/hospital/$id',
  path: '/hospital/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalAdminLoginRoute = HospitalAdminLoginRouteImport.update({
  id: '/hospital-admin/login',
  path: '/hospital-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/hospital-admin/login': typeof HospitalAdminLoginRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/hospital-admin/': typeof HospitalAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/hospital-admin/login': typeof HospitalAdminLoginRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/hospital-admin': typeof HospitalAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/hospital-admin/login': typeof HospitalAdminLoginRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/hospital-admin/': typeof HospitalAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmation'
    | '/login'
    | '/payment'
    | '/hospital-admin/login'
    | '/hospital/$id'
    | '/hospital-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmation'
    | '/login'
    | '/payment'
    | '/hospital-admin/login'
    | '/hospital/$id'
    | '/hospital-admin'
  id:
    | '__root__'
    | '/'
    | '/confirmation'
    | '/login'
    | '/payment'
    | '/hospital-admin/login'
    | '/hospital/$id'
    | '/hospital-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmationRoute: typeof ConfirmationRoute
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  HospitalAdminLoginRoute: typeof HospitalAdminLoginRoute
  HospitalIdRoute: typeof HospitalIdRoute
  HospitalAdminIndexRoute: typeof HospitalAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-admin/': {
      id: '/hospital-admin/'
      path: '/hospital-admin'
      fullPath: '/hospital-admin/'
      preLoaderRoute: typeof HospitalAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/$id': {
      id: '/hospital/$id'
      path: '/hospital/$id'
      fullPath: '/hospital/$id'
      preLoaderRoute: typeof HospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-admin/login': {
      id: '/hospital-admin/login'
      path: '/hospital-admin/login'
      fullPath: '/hospital-admin/login'
      preLoaderRoute: typeof HospitalAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmationRoute: ConfirmationRoute,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  HospitalAdminLoginRoute: HospitalAdminLoginRoute,
  HospitalIdRoute: HospitalIdRoute,
  HospitalAdminIndexRoute: HospitalAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
